[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "moz-idb-edit"
version = "0.2.1"
requires-python = ">=3.8"
dependencies = [
	"jmespath ~= 1.0",
]

[project.scripts]
moz-idb-edit = "mozidbedit:main"
